[package]
org = "ballerina"
name = "tcp"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["network", "socket", "service", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-tcp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0-20250226-081700-17d84e0f"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "tcp-native"
version = "@toml.version@"
path = "../native/build/libs/tcp-native-@project.version@.jar"

[[platform.java21.dependency]]
path = "../test-utils/build/libs/tcp-test-utils-@project.version@.jar"
scope = "testOnly"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "@netty.version@"
path = "./lib/netty-handler-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "@netty.version@"
path = "./lib/netty-buffer-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "@netty.version@"
path = "./lib/netty-transport-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "@netty.version@"
path = "./lib/netty-common-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "@netty.version@"
path = "./lib/netty-resolver-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "@netty.version@"
path = "./lib/netty-codec-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-unix-common"
version = "@netty.version@"
path = "./lib/netty-transport-native-unix-common-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-socks"
version = "@netty.version@"
path = "./lib/netty-codec-socks-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "org.jboss.marshalling"
artifactId = "jboss-marshalling"
version = "@marshalling.version@"
path = "./lib/jboss-marshalling-@marshalling.version@.jar"

[[platform.java21.dependency]]
groupId = "net.jpountz.lz4"
artifactId = "lz4"
version = "@lz4.version@"
path = "./lib/lz4-@lz4.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.protobufl"
artifactId = "protobuf-java"
version = "@protobuf.version@"
path = "./lib/protobuf-java-@protobuf.version@.jar"
