[package]
org = "ballerina"
name = "tcp"
version = "1.5.0"
authors = ["Ballerina"]
keywords = ["network", "socket", "service", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-tcp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.3.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "tcp-native"
version = "1.5.0"
path = "../native/build/libs/tcp-native-1.5.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/tcp-test-utils-1.5.0-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.78.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.78.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.78.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.78.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.78.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.78.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-native-unix-common-4.1.78.Final.jar"
