[package]
org = "ballerina"
name = "tcp"
version = "1.2.0"
authors = ["Ballerina"]
keywords = ["network", "socket", "service", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-tcp"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/tcp-native-1.2.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/tcp-test-utils-1.2.0-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.71.Final.jar"
