[package]
org = "ballerina"
name = "tcp"
version = "1.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/tcp-native-1.0.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/tcp-test-utils-1.0.0-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.68.Final.jar"
