[package]
org = "ballerina"
name = "tcp"
version = "1.7.3"
authors = ["Ballerina"]
keywords = ["network", "socket", "service", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-tcp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.5.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "tcp-native"
version = "1.7.3"
path = "../native/build/libs/tcp-native-1.7.3.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/tcp-test-utils-1.7.3.jar"
scope = "testOnly"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.100.Final"
path = "./lib/netty-handler-4.1.100.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.100.Final"
path = "./lib/netty-buffer-4.1.100.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.1.100.Final"
path = "./lib/netty-transport-4.1.100.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.100.Final"
path = "./lib/netty-common-4.1.100.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.1.100.Final"
path = "./lib/netty-resolver-4.1.100.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "4.1.100.Final"
path = "./lib/netty-codec-4.1.100.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-unix-common"
version = "4.1.100.Final"
path = "./lib/netty-transport-native-unix-common-4.1.100.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-socks"
version = "4.1.100.Final"
path = "./lib/netty-codec-socks-4.1.100.Final.jar"

[[platform.java11.dependency]]
groupId = "org.jboss.marshalling"
artifactId = "jboss-marshalling"
version = "2.0.5.Final"
path = "./lib/jboss-marshalling-2.0.5.Final.jar"

[[platform.java11.dependency]]
groupId = "net.jpountz.lz4"
artifactId = "lz4"
version = "1.3.0"
path = "./lib/lz4-1.3.0.jar"

[[platform.java11.dependency]]
groupId = "com.google.protobufl"
artifactId = "protobuf-java"
version = "3.20.3"
path = "./lib/protobuf-java-3.20.3.jar"
