[package]
org = "ballerina"
name = "tcp"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../tcp-native/build/libs/tcp-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "tcp"
version = "@project.version@"

[[platform.java11.dependency]]
path = "../tcp-test-utils/build/libs/tcp-test-utils-@project.version@.jar"
groupId = "org.ballerinalang.stdlib.tcp"
scope = "testOnly"
artifactId = "tcp"
version = "@project.version@"

[[platform.java11.dependency]]
artifactId = "netty-handler"
version = "@netty.version@"
path = "./build/libs/netty-handler-@netty.version@.jar"
groupId = "io.netty"

[[platform.java11.dependency]]
artifactId = "netty-buffer"
version = "@netty.version@"
path = "./build/libs/netty-buffer-@netty.version@.jar"
groupId = "io.netty"

[[platform.java11.dependency]]
artifactId = "netty-transport"
version = "@netty.version@"
path = "./build/libs/netty-transport-@netty.version@.jar"
groupId = "io.netty"

[[platform.java11.dependency]]
artifactId = "netty-common"
version = "@netty.version@"
path = "./build/libs/netty-common-@netty.version@.jar"
groupId = "io.netty"

[[platform.java11.dependency]]
artifactId = "netty-resolver"
version = "@netty.version@"
path = "./build/libs/netty-resolver-@netty.version@.jar"
groupId = "io.netty"

[[platform.java11.dependency]]
artifactId = "netty-resolver"
version = "@netty.version@"
path = "./build/libs/netty-codec-@netty.version@.jar"
groupId = "io.netty"
